## Final Project Submission

Please fill out:
* Student name: 
* Student pace: self paced / part time / full time
* Scheduled project review date/time: 
* Instructor name: 
* Blog post URL:

In [27]:
# Your code here - remember to use markdown cells for comments as well

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('./data/Aviation_Data.csv')

In [13]:
#Transform the Event Date into three separate Date columns that specify day, month and year of the incident

df['Event.Date'] = pd.to_datetime(df['Event.Date'])
df['Event.Day'] = df['Event.Date'].map(lambda x: x.day)
df['Event.Month'] = df['Event.Date'].map(lambda x: x.month)
df['Event.Year'] = df['Event.Date'].map(lambda x: x.year)

In [3]:
#Grouping all the Countries outside of the US as "Foreign Country"
df.loc[df['Country'] != 'United States', 'Country'] = 'Foreign Country'

In [4]:
#Filling the Null Values with "UNKNOWN" the the Location Column
df['Location'] = df['Location'].fillna('UNKNOWN')

In [5]:
# Creating an 'State' column with just the code for the corresponding State, if it's not in the US it'll show the whole location.
df['State'] = df['Location'].apply(lambda location: location.split(', ')[-1] if len(location.split(', ')) > 1 and len(location.split(', ')[-1]) == 2 else 'Foreign Location')

In [162]:
#Cleaning the 'Make' Column
characters_to_remove = ['(', ')', ',', '.', '%', '?']
df['Make'] = df['Make'].str.title().fillna('UNKNOWN')
df['Make'] = df['Make'].map(lambda x: ''.join(char for char in x if char not in characters_to_remove))

In [112]:
df['Airport.Name'] = df['Airport.Name'].str.title().fillna('UNKNOWN')

In [104]:
#NOT SURE IF its worth to use, doen't eliminate anything
#df['Airport.Name'] = df['Airport.Name'].map(lambda x: ''.join(char for char in x if char not in characters_to_remove))

In [109]:
df['Airport.Name'] = df['Airport.Name'].str.contains('Private', case=False).sum()

In [113]:
#mask = df['text_column'].str.contains(target_string, case=False)
df.loc[df['Airport.Name'].str.contains('private', case=False), 'Airport.Name'] = 'Private'

In [10]:
df.loc[df['State']]

KeyError: True

In [6]:
df.loc[(df['Country'] == 'United States') & (len(df['State']) > 2)]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,State
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN,ID
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996,CA
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.9222,-81.8781,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007,VA
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000,CA
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980,OH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90343,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022,MD
90344,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NH
90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022,AZ
90346,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,UT
90347,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022,GA

In [166]:
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

In [130]:
df.loc[(df['State'].str.len() >2) & (df['Country'] == 'United States')]

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date,State
3446,20020917X04798,Accident,LAX83FA055,1982-12-09,"500 NM E, HONOLULU, HI",United States,NaN,NaN,NaN,UNKNOWN,...,NaN,2.0,NaN,NaN,NaN,VMC,Cruise,Probable Cause,02-02-2016,"500 NM E, HONOLULU, HI"
4239,20001214X42513,Accident,LAX83LAMS4,1983-03-29,UNKNOWN,United States,NaN,NaN,NaN,UNKNOWN,...,NaN,1.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,NaN,UNKNOWN
4298,20001214X42715,Accident,LAX83FJA06,1983-04-03,"WAIMANALO, OAHU, HI",United States,NaN,NaN,NaN,UNKNOWN,...,NaN,1.0,1.0,2.0,0.0,VMC,Maneuvering,Probable Cause,NaN,"WAIMANALO, OAHU, HI"
8228,20001214X39646,Accident,LAX84LA307,1984-05-12,"TAU, MANU'A, HI",United States,NaN,NaN,TAU,Tau,...,NaN,0.0,0.0,0.0,20.0,VMC,Landing,Probable Cause,NaN,"TAU, MANU'A, HI"
10546,20001214X41859,Accident,MIA85LAMS1,1984-12-23,UNKNOWN,United States,NaN,NaN,NaN,UNKNOWN,...,NaN,1.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,NaN,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84468,20190711X52011,Accident,GAA19CA404,2019-07-10,"Saipan,",United States,015726N,1454353E,PGSN,Saipan International Airport,...,Marianas Air Transfer Inc,0.0,0.0,0.0,3.0,VMC,NaN,The pilot's failure to maintain directional co...,26-09-2020,"Saipan,"
84892,20190912X74625,Accident,ERA19LA279,2019-09-12,"Charlotte Amalie,",United States,182015N,0064582W,TIST,Cyril E King,...,Executive Airshares Llc,0.0,0.0,0.0,1.0,VMC,NaN,The collapse of the left main landing gear for...,NaN,"Charlotte Amalie,"
84909,20190916X82539,Accident,CEN19TA321,2019-09-15,"Gulf of Mexico,",United States,028521N,0089188W,NaN,UNKNOWN,...,NaN,0.0,0.0,0.0,1.0,VMC,NaN,A loss of engine power for undetermined reason...,28-01-2021,"Gulf of Mexico,"
85054,20191021X53431,Accident,CEN20LA021,2019-10-17,"Unknown,",United States,252257N,0090733W,NaN,UNKNOWN,...,NaN,1.0,0.0,0.0,0.0,VMC,NaN,NaN,13-12-2021,"Unknown,"
85835,20200601X20239,Accident,ERA20CA201,2020-06-01,"GULF OF MEXICO,",United States,026054N,0082645W,NaN,UNKNOWN,...,NaN,0.0,0.0,0.0,2.0,VMC,NaN,A total loss of engine power due to a fuel lea...,29-01-2021,"GULF OF MEXICO,"

In [ ]:
# Event.Id
# Investigation.Type
# Accident.Number
# Event.Date
# Location
# Country
# Injury.Severity
# Aircraft.damage
# Registration.Number 
# Make #keep, maybe use to engineer a new feature using LLM 
# Model #keep, maybe use to engineer a new feature using LLM 
# Amateur.Built #keep: few nan (1.5k) vals, most are not amateur built (80k)
# Number.of.Engines #keep: few NAN values (7.5k), most are have 1 (70k)
# Engine.Type #keep, few unknown (2k) and nan vals (8.5k), most are reciprocating (70k)
# Purpose.of.flight #keep: few unknown (6.8k) and nan (7.6k) vals, most are personal (50k)
# Total.Fatal.Injuries #keep
# Total.Serious.Injuries #keep
# Total.Minor.Injuries #keep
# Total.Uninjured #keep
# Weather.Condition #keep, mostly split between low and high visibility 
# Report.Status #DROP, about 70k are probable cause or nan 
# Publication.Date #DROP, less important than event date; also, skewed towards 2020

In [ ]:
"""Actions to take with the null values per column:
Event.Id                  0.016149
Investigation.Type        0.000000 DROP
Accident.Number           0.016149
Event.Date                0.016149
Location                  0.016724
Country                   0.018650
Latitude                  0.619449  DROP COLUMN
Longitude                 0.619549 DROP COLUMN
Airport.Code              0.443828
Airport.Name              0.415704
Injury.Severity           0.027217
Aircraft.damage           0.051501
Aircraft.Category         0.642637
Registration.Number       0.030726 
Make                      0.016846 DROP
Model                     0.017167 DROP
Amateur.Built             0.017278 
Number.of.Engines         0.083488
Engine.Type               0.094479
FAR.Description           0.645559
Schedule                  0.860738
Purpose.of.flight         0.084684
Air.carrier               0.815735
Total.Fatal.Injuries      0.142339
Total.Serious.Injuries    0.154613
Total.Minor.Injuries      0.148227
Total.Uninjured           0.081585
Weather.Condition         0.065868
Broad.phase.of.flight     0.316819
Report.Status             0.086776 DROP
Publication.Date          0.184719
"""

In [35]:
# We're going to ignore the Aircraft.Category for now, 
#then check correlations of unknowns with the ones from aircrafts
#We replace the null values on the aircraft category for "Unknown" to don't discard the type completely
df['Aircraft.Category'] = df['Aircraft.Category'].fillna('Unknown')

In [ ]:
'''Event.Id              1459 DROP COLUMN
Investigation.Type       0  DROP COLUMN
Accident.Number       1459 DROP COLUMN
Event.Date            1459 CHANGE TO EVENT YEAR 
Location              1511
Country               1685 US - NON US
Injury.Severity       2459 DROP COLUMN
Aircraft.damage       4653'''